"""Sentinel-1/2 satellite imagery client.

Provides access to Copernicus Data Space Ecosystem (free) for
Sentinel-2 multispectral (10m, 13 bands, 5-day revisit) and
Sentinel-1 SAR (cloud-penetrating, 6-12 day revisit) imagery.

In demo mode: returns paths to pre-generated synthetic tiles.
"""

from __future__ import annotations

import os
from datetime import datetime, timedelta
from pathlib import Path
from typing import Optional

import structlog

logger = structlog.get_logger(__name__)

# Demo tile locations
_DATA_DIR = Path(__file__).resolve().parent.parent / "data"
_SENTINEL2_DIR = Path(__file__).resolve().parent.parent.parent.parent / "data" / "sentinel2"


class SentinelClient:
    """Client for Copernicus Sentinel-1/2 satellite imagery.

    Downloads Sentinel-1/2 tiles from Copernicus Data Space Ecosystem (free API).
    - Sentinel-2: 10m resolution, 13 spectral bands, 5-day revisit
    - Sentinel-1: SAR, sees through clouds/darkness, 6-12 day revisit

    In demo mode, returns pre-generated synthetic tiles.
    """

    BASE_URL = "https://dataspace.copernicus.eu/odata/v1"

    def __init__(
        self,
        client_id: str = "",
        client_secret: str = "",
        demo_mode: bool = True,
    ):
        self.demo_mode = demo_mode
        self.client_id = client_id
        self.client_secret = client_secret
        self.token: Optional[str] = None

        if not demo_mode and client_id and client_secret:
            try:
                self.token = self._get_access_token(client_id, client_secret)
                logger.info("sentinel_authenticated", api="copernicus")
            except Exception as e:
                logger.warning("sentinel_auth_failed", error=str(e))
                self.demo_mode = True
        else:
            logger.info("sentinel_demo_mode", reason="no credentials or demo_mode=True")

    # ── Authentication ───────────────────────────────────────────────────

    def _get_access_token(self, client_id: str, client_secret: str) -> str:
        """Obtain OAuth2 token from Copernicus Data Space."""
        try:
            import httpx

            resp = httpx.post(
                "https://identity.dataspace.copernicus.eu/auth/realms/"
                "CDSE/protocol/openid-connect/token",
                data={
                    "grant_type": "client_credentials",
                    "client_id": client_id,
                    "client_secret": client_secret,
                },
                timeout=10.0,
            )
            resp.raise_for_status()
            return resp.json()["access_token"]
        except Exception as e:
            raise RuntimeError(f"Copernicus auth failed: {e}") from e

    # ── Download Methods ─────────────────────────────────────────────────

    def download_sentinel2_tile(
        self,
        bbox: tuple,
        date_from: datetime,
        date_to: datetime,
        max_cloud_pct: float = 20.0,
    ) -> Optional[str]:
        """Download least-cloudy Sentinel-2 L2A tile for bbox and date range.

        Returns: local file path to downloaded tile (or None if unavailable).
        """
        if self.demo_mode:
            logger.info("sentinel2_demo_download", bbox=bbox)
            return str(self._get_demo_before_path())

        # Production: query Copernicus OData API
        logger.info(
            "sentinel2_download",
            bbox=bbox,
            date_from=date_from.isoformat(),
            date_to=date_to.isoformat(),
            max_cloud=max_cloud_pct,
        )
        return None  # Placeholder for real implementation

    def download_sentinel1_sar(
        self, bbox: tuple, date: datetime
    ) -> Optional[str]:
        """Download Sentinel-1 GRD SAR tile (flood extent confirmation).

        Returns: local file path to downloaded tile.
        """
        if self.demo_mode:
            logger.info("sentinel1_demo_download", bbox=bbox)
            sar_path = _SENTINEL2_DIR / "beas_valley_2023_08_flood_sar.npy"
            return str(sar_path) if sar_path.exists() else None

        logger.info("sentinel1_download", bbox=bbox, date=date.isoformat())
        return None

    # ── Demo Tiles ───────────────────────────────────────────────────────

    def get_demo_tiles(self) -> dict:
        """Return paths to pre-generated demo tiles (Beas Valley, Himachal Pradesh).

        These are generated by scripts/generate_synthetic_sentinel_tiles.py
        and committed to data/sentinel2/.

        CRITICAL: demo must never depend on live satellite download.
        """
        before = self._get_demo_before_path()
        after = self._get_demo_after_path()
        sar = _SENTINEL2_DIR / "beas_valley_2023_08_flood_sar.npy"

        return {
            "before": str(before) if before.exists() else None,
            "after": str(after) if after.exists() else None,
            "sar_flood": str(sar) if sar.exists() else None,
            "before_date": "2022-08-15",
            "after_date": "2023-09-15",
            "location": "Beas Valley, Himachal Pradesh",
            "bbox": (77.05, 31.80, 77.30, 32.05),
        }

    def _get_demo_before_path(self) -> Path:
        """Resolve before tile path, trying .tif then .npy."""
        tif = _SENTINEL2_DIR / "beas_valley_2022_08_before.tif"
        npy = _SENTINEL2_DIR / "beas_valley_2022_08_before.npy"
        return tif if tif.exists() else npy

    def _get_demo_after_path(self) -> Path:
        """Resolve after tile path, trying .tif then .npy."""
        tif = _SENTINEL2_DIR / "beas_valley_2023_09_after.tif"
        npy = _SENTINEL2_DIR / "beas_valley_2023_09_after.npy"
        return tif if tif.exists() else npy

    def tiles_available(self) -> bool:
        """Check if demo tiles have been generated."""
        tiles = self.get_demo_tiles()
        return tiles["before"] is not None and tiles["after"] is not None
